### PR TITLE
Freature: Added a new filr in dev branch

### PR DESCRIPTION
**Pull request by Salman8853**
Added a new feature to dev branch and wants to pull it in master branch..!!

### CODE REVIEW

**Comment by Salman8853** [comment]
Hi krishna I made a PR(Pull Request) for dev brach added a new feature. Kindly go through it and either accept it or give the genuien reason for declined... !!
Thanks

**Comment by Krishna8853** [comment]
Every this is good to go

**Review by Krishna8853 — APPROVED** [review]
GTG

**Comment by Krishna8853** [comment]
merge done

**Pull request merged**
